# use this example for config_real.yml

databases:
  host: "host url"
  port: 3306
  database: "db name"
  username: "username"
  password: "passwd"
  timezone: "+09:00"

secrets:
  django: "django-something-something"

token:
  scret: "something_secret"
  expire_sec: 3600