# Generated by Django 4.1.3 on 2022-11-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None)),
                ("email", models.CharField(default="", max_length=50, unique=True)),
                ("password", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "user",
                "abstract": False,
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None)),
                ("token", models.CharField(default=None, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_token",
                "abstract": False,
                "managed": True,
            },
        ),
    ]
